name: 🐛 Bug Report
description: Reporte um problema encontrado no projeto
title: "[BUG] "
labels: ["bug"]

body:
  - type: textarea
    id: descricao
    attributes:
      label: 🚧 Descrição do problema
      description: Explique claramente o que está acontecendo.
      placeholder: |
        Descreva o bug com o máximo de detalhe possível.

  - type: textarea
    id: passos
    attributes:
      label: 🔁 Passos para reproduzir
      description: Liste como reproduzir o erro.
      placeholder: |
        1. Vá até '...'
        2. Clique em '...'
        3. Observe o erro

  - type: textarea
    id: comportamento
    attributes:
      label: ❌ Comportamento atual
      description: O que está acontecendo de errado?
      placeholder: |
        Descreva o comportamento atual.

  - type: textarea
    id: esperado
    attributes:
      label: ✅ Comportamento esperado
      description: O que deveria acontecer?
      placeholder: |
        Descreva o comportamento correto esperado.

  - type: textarea
    id: contexto
    attributes:
      label: 🧠 Contexto adicional
      description: Logs, screenshots ou qualquer informação útil
      placeholder: |
        Cole aqui erros do console, imagens ou detalhes extras.
